name: Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build:
    name: Documentation deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
          toolchain: stable

      - name: Install NodeJS v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Version output
        run: |
          rustc --version
          cargo --version
          node --version
          npm --version

      - name: Install mdbook
        run: cargo install mdbook

      - name: Build documentation
        run: mdbook build docs

      - name: Deploy with gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d docs/book -u "github-actions-bot <support+actions@github.com>"
